TAB			.equ		0x09
NULL 		.equ		0x00 
BS 			.equ		0x08
SPC			.equ		0x20
CR			.equ		0x0a
LF			.equ		0x0d
DEL			.equ		0x7f

.globl title_str
.globl newline_str
.globl command_prompt_str
.globl help_table
.globl app_table
.globl help_txt
.globl ls_txt
.globl peek_txt
.globl poke_txt
.globl clear_txt
.globl reset_txt
.globl write_txt
.globl dump_txt
.globl fill_txt
.globl copy_txt
.globl goto_txt
.globl iram_txt
.globl sfr_txt
.globl msg_err

